services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  webserver:
    build: .  # This will build from the Dockerfile in the current directory
    container_name: airflow_webserver
    restart: always
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW_CONN_POSTGRES_DEFAULT=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__WEBSERVER__SECRET_KEY=rsM6bMb73JXTyodAJ8IQug==
      - _AIRFLOW_WWW_USER_USERNAME=admin
      - _AIRFLOW_WWW_USER_PASSWORD=admin
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./datasets:/opt/airflow/datasets
    entrypoint: ["/bin/bash", "-c", "
        until pg_isready -h postgres -U airflow; do echo 'Waiting for postgres'; sleep 2; done &&
        airflow db upgrade && 
        if ! airflow users list | grep -q admin; then
          airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin;
        fi &&
        airflow webserver
      "]

  scheduler:
    build: .  # Same as webserver
    container_name: airflow_scheduler
    restart: always
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW_CONN_POSTGRES_DEFAULT=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__WEBSERVER__SECRET_KEY=rsM6bMb73JXTyodAJ8IQug==
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./datasets:/opt/airflow/datasets
    entrypoint: ["/bin/bash", "-c", "airflow scheduler"]

volumes:
  postgres_data:

